name: cipher_affair
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter_bloc: ^8.1.5
  auto_size_text: ^3.0.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.17.0
  bloc: ^8.1.4
  video_player: ^2.8.6
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  flutter_shakemywidget: ^1.0.5+1
  just_audio: ^0.9.37
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/carousel/
    - assets/loading_assets/
    - assets/videos/
    - assets/carousel/level_1_carousel/
    - assets/music/



  fonts:
    - family: Legio
      fonts:
        - asset: fonts/LegioSabina3DRegular-7BaoA.otf
        - asset: fonts/LegioSabinaBold-d9DlX.otf

    - family: Kod
      fonts:
        - asset: fonts/Kodchasan-Regular.ttf
       

