name: cipher_affair
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter_bloc: ^8.1.5
  auto_size_text: ^3.0.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.17.0
  bloc: ^8.1.4
  video_player: ^2.8.6
  carousel_slider: ^4.2.1
  animated_text_kit: ^4.2.2
  animated_widgets: ^1.1.0
  flutter_shakemywidget: ^1.0.5+1
  just_audio: ^0.9.37
  assets_audio_player: ^3.1.1
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  flutter_timer_countdown: ^1.0.7
  circular_countdown_timer: ^0.2.3
  just_audio_background: ^0.0.1-beta.11
  flutter_background_service: ^5.0.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/cipher_scape_logo1.png"

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/loading_assets/
    - assets/music/
    - assets/carousel/
    - assets/backgrounds/
    - assets/level_assets/l1_b/
    - assets/level_assets/l1_a/
    - assets/level_assets/l2_b/
    - assets/level_assets/l2_a/
    - assets/level_assets/l3_b/
    - assets/level_assets/l3_a/



  fonts:
    - family: Legio
      fonts:
        - asset: fonts/LegioSabina3DRegular-7BaoA.otf
        - asset: fonts/LegioSabinaBold-d9DlX.otf

    - family: Kod
      fonts:
        - asset: fonts/Kodchasan-Regular.ttf

    - family: JetBrains
      fonts:
        - asset : fonts/JetBrainsMonoNL-Regular.ttf

    - family: Fira
      fonts:
        - asset : fonts/FiraCode-Regular.ttf
       

